version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: fred-tracker
    volumes:
      - ./pg_data:/var/lib/postgresql/data # Persist data on your host
    ports:
      - "5432:5432" # Optional: allows connection from outside Docker

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80" # Access pgAdmin in browser at http://localhost:8080
  app:
    image: fred-tracker
    ports:
      - "13000:3000"